// ng-tailwind-component/src/app/component/image/image.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-image',
  templateUrl: './image.component.html',
  styleUrls: ['./image.component.scss']
})
export class ImageComponent implements OnInit {
  @Input() src: string = '';
  @Input() width: number = 0;
  @Input() height: number = 0;

  ngOnInit() { }

}

<div class="flex justify-center items-center bg-gray-100" [ngStyle]="{'width': width + 'px', 'height': height + 'px'}">
  <img class="max-w-full max-h-full" [src]="src">
</div>

// react-component/src/component/Image/Image.tsx
import React from 'react';
import styled, {css} from 'styled-components';


type ImageProps = {
  src: string;
  width: number;
  height: number;
};

const Wrapper = styled.div<Pick<ImageProps, 'width' | 'height'>>`
  background-color: #EEE;
  display: flex;
  align-items: center;
  justify-content: center;
  width: ${({width}) => width}px;
  height: ${({height}) => height}px;
`;
const Image = styled.img`
  max-width: 100%;
  max-height: 100%;
`;

export const ImageComponent: React.FC<ImageProps> = ({src, width, height}) => <Wrapper width={width} height={height}>
  <Image src={src}></Image>
</Wrapper>;
